# تكوين Upptime
sites:
  - name: My Streamlit App # اسم تطبيقك
    url: https://disaster-app.streamlit.app # ضع رابط تطبيقك الحقيقي هنا

status-website:
  # إعدادات الموقع (لا تغيرها الآن)
  baseUrl: "/"
  logoUrl: https://github.com/upptime/upptime/raw/master/static/img/icon.svg
  name: Status Page
